services:
  php-apache:
    container_name: sisodonto
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/html/sisodonto

  mysql:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    ports:
      - 33060:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Manaus
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data:/var/lib/mysql
      - ./dumps:/dumps
      - ./scripts:/scripts
      - ./initdb:/docker-entrypoint-initdb.d
